In [119]:
import pandas as pd
import numpy as np

In [120]:
df = pd.read_csv('pre.csv')
df = df.replace('-', 0)
df = df.replace('T', 0)
df = df.drop(df.index[334:365])
df = df.drop('Date', axis=1)
df.shape
#df['PrecipitationSumInches'].values[0]

(334, 19)

In [121]:
print(np.mean(df['DewPointHighF'].astype(float)))
print(np.median(df['DewPointHighF'].astype(float)))

59.32634730538922
64.5


In [122]:
list = df.columns

In [123]:
for i in list:
    df[i] = df[i].astype(float)

In [148]:
x = df.drop('PrecipitationSumInches',axis=1)
y = df['PrecipitationSumInches']
y = y[:,None]
print(y)

[[0.46]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.16]
 [0.  ]
 [0.1 ]
 [0.  ]
 [0.01]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.06]
 [0.05]
 [0.  ]
 [0.  ]
 [0.02]
 [0.05]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.02]
 [0.  ]
 [0.15]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.1 ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.11]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.08]
 [0.08]
 [0.17]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.74]
 [0.11]
 [0.01]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.07]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.01]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.2 ]
 [0.27]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [0.  ]
 [1.34]
 [0.  ]
 [0.  ]
 [0.06]
 [0.01]
 [0.  ]
 [0.  ]
 [0.01]
 [0.  ]
 [0.  ]
 [0.  ]


In [149]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
xt = scaler.fit_transform(x)
yt= scaler.fit_transform(y)
print(yt)
x.shape
yi=scaler.inverse_transform(yt)
print(yi)

[[0.12568306]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.04371585]
 [0.        ]
 [0.0273224 ]
 [0.        ]
 [0.00273224]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.01639344]
 [0.0136612 ]
 [0.        ]
 [0.        ]
 [0.00546448]
 [0.0136612 ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.00546448]
 [0.        ]
 [0.04098361]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.0273224 ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.03005464]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.02

In [150]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split# Instantiate model with 1000 decision trees
x_train, x_test, y_train, y_test = train_test_split(xt, yt, test_size = 0.25)
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)# Train the model on training data
rf.fit(x_train, y_train)

<ipython-input-150-1575e0d7741b>:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(x_train, y_train)


RandomForestRegressor(n_estimators=1000, random_state=42)

In [151]:
predictions = rf.predict(x_test)# Calculate the absolute errors
errors = abs(predictions - y_test)# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 0.05 degrees.


In [152]:
mape = 100 * (errors / y_test)# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: nan %.


<ipython-input-152-b37ced1946fb>:1: RuntimeWarning: divide by zero encountered in true_divide
  mape = 100 * (errors / y_test)# Calculate and display accuracy
<ipython-input-152-b37ced1946fb>:1: RuntimeWarning: invalid value encountered in true_divide
  mape = 100 * (errors / y_test)# Calculate and display accuracy


In [156]:
p = scaler.inverse_transform(predictions.reshape(-1,1))
y = scaler.inverse_transform(y_test.reshape(-1,1))
print(p)
print(y)

[[3.00000e-04]
 [7.08080e-01]
 [1.01180e-01]
 [1.95040e-01]
 [1.35700e-02]
 [6.00000e-05]
 [0.00000e+00]
 [2.10000e-04]
 [0.00000e+00]
 [4.10950e-01]
 [0.00000e+00]
 [5.35700e-02]
 [1.15970e-01]
 [1.41380e-01]
 [0.00000e+00]
 [8.16000e-03]
 [4.75800e-02]
 [6.00000e-05]
 [1.75000e-03]
 [7.70000e-04]
 [1.11000e-03]
 [7.01000e-03]
 [4.60000e-03]
 [2.64700e-02]
 [1.90000e-04]
 [8.00590e-01]
 [0.00000e+00]
 [0.00000e+00]
 [1.23000e-03]
 [2.58840e-01]
 [4.00000e-05]
 [0.00000e+00]
 [2.88300e-02]
 [2.68260e-01]
 [0.00000e+00]
 [1.42020e-01]
 [1.00000e-05]
 [9.03170e-01]
 [3.40000e-04]
 [0.00000e+00]
 [8.10260e-01]
 [8.00000e-05]
 [2.00000e-05]
 [2.48000e-03]
 [1.06000e-03]
 [3.25000e-03]
 [6.27000e-03]
 [1.40000e-04]
 [3.33000e-03]
 [4.36800e-02]
 [1.30000e-04]
 [5.68500e-02]
 [3.22000e-03]
 [2.63200e-02]
 [0.00000e+00]
 [6.00000e-03]
 [3.71860e-01]
 [2.75280e-01]
 [1.27205e+00]
 [2.23500e-02]
 [6.78500e-02]
 [1.17160e-01]
 [1.63400e-02]
 [0.00000e+00]
 [1.70000e-04]
 [4.02100e-02]
 [3.07000e